### ISSUE TITLE
Potentially useful additions

### ISSUE THREAD

**Issue by vincentjames501** [Telenav/ExpandablePager#1]
## OnSliderStateChangeListener

It would be nice to include the page positions like so:

``` java
public interface OnSliderStateChangeListener {
    void onStateChanged(View page,@SlidingContainer.SliderState int state, int position);
    void onPageChanged(View page,@SlidingContainer.SliderState int state, int position);
}
```
## ExpandablePager

You can call `setCurrentItem(...)` but there should be a `getCurrentItem()` as well.
## ExpandablePagerAdapter

It would be nice if you could also extend `FragmentPagerAdapter`. I'd like to use fragments instead of views for this.

**Comment by dimatim** [comment]
Great suggestions!
all these features are available in 234bfd1 and version `0.2.0`
